"""Canonicalising a question before it is retrieved with, and cached against.

THE PROBLEM, measured on this corpus. Four phrasings of one question retrieved the same
set of chunks in only 18.5% of pairs (mean Jaccard 0.55). Different chunk sets mean
different prompts, which means no shared prefix, which means every paraphrase pays a full
prefill. Ordering the chunks deterministically was worth +0.9% shared prefix, because
ordering only helps the 2.3% of pairs that already retrieved the same set in a different
order. The chunk set is the lever, and the chunk set is decided by the query.

WHAT IS STRIPPED. Discourse lead-ins: the conversational framing a person puts in front
of a question that carries no information about which document answers it. "Cho tôi biết:
X" and "X" should retrieve identically, because they are the same question. The list below
is curated Vietnamese conversational openers, not a regex fitted to one dataset.

HONEST LIMIT, because it changes how the measured gain should be read. The evaluation
variants here were generated by prepending one of three fixed templates, so a lead-in
stripper is unusually well matched to them and the improvement it shows is an upper
bound. Real users paraphrase by rewording the question itself -- "khi nào thì tính là
chuyến hoàn thành" against "điều kiện để một chuyến được tính hoàn thành" -- and no amount
of prefix stripping merges those two. Closing that gap needs retrieval that is robust to
rewording, which is the dense side of the hybrid, not this module. Treat what follows as
the cheap half of the problem, done first because it costs nothing at runtime.

WHAT IS DELIBERATELY NOT STRIPPED. Anything that changes the answer. "Theo định nghĩa
hiện hành" reads like framing, and in this eval set it is, but "theo định nghĩa CŨ" is a
genuine scope change that must reach rag.policy so it can unsuppress the deprecated
documents. Recency and scope markers are therefore extracted into a hint rather than
discarded, and the caller decides what to do with them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from rag.text_vi import normalise

# Conversational openers. Matched at the start only, and repeatedly, so "Cho tôi biết:
# theo định nghĩa hiện hành, X" reduces cleanly.
_LEAD_INS = (
    r"cho\s+tôi\s+biết",
    r"cho\s+mình\s+hỏi",
    r"cho\s+hỏi",
    r"tôi\s+muốn\s+biết",
    r"mình\s+muốn\s+hỏi",
    r"bạn\s+có\s+thể\s+cho\s+biết",
    r"vui\s+lòng\s+cho\s+biết",
    r"giải\s+thích\s+giúp\s+tôi",
    r"theo\s+định\s+nghĩa\s+hiện\s+hành",
    r"theo\s+quy\s+định\s+hiện\s+hành",
    r"theo\s+tài\s+liệu\s+hiện\s+hành",
    r"trong\s+bộ\s+dữ\s+liệu\s+demo",
    r"trong\s+hệ\s+thống",
    r"hiện\s+tại",
    r"hiện\s+nay",
)

_LEAD_RE = re.compile(
    r"^\s*(?:" + "|".join(_LEAD_INS) + r")\s*[:,\-–]?\s*", re.IGNORECASE)

# Markers that look like framing but change which documents are in scope. Extracted, not
# removed, because rag.policy needs them.
_SCOPE_MARKERS = (
    ("historical", re.compile(
        r"(định\s+nghĩa\s+cũ|quy\s+tắc\s+cũ|trước\s+đây|ngày\s+trước|phiên\s+bản\s+cũ|"
        r"đã\s+hết\s+hiệu\s+lực|trước\s+khi\s+đổi)", re.IGNORECASE)),
    ("draft", re.compile(r"(bản\s+nháp|đang\s+đề\s+xuất|chưa\s+phê\s+duyệt)", re.IGNORECASE)),
)

_TRAILING_POLITENESS = re.compile(
    r"\s*(nhé|nha|ạ|với ạ|giúp tôi|giúp mình|được không|vậy)\s*[?？.!]*\s*$",
    re.IGNORECASE)


@dataclass(frozen=True)
class CanonicalQuery:
    text: str            # what retrieval and the cache key see
    original: str        # what the user typed, kept for logs and for the answer
    scope: str | None    # "historical" | "draft" | None
    stripped: tuple[str, ...]

    @property
    def changed(self) -> bool:
        return self.text != self.original


def canonicalise(question: str) -> CanonicalQuery:
    original = normalise(question)
    text = original
    stripped: list[str] = []

    scope: str | None = None
    for name, rx in _SCOPE_MARKERS:
        if rx.search(text):
            scope = name
            break

    # Peel repeatedly: users stack lead-ins.
    while True:
        m = _LEAD_RE.match(text)
        if not m or not m.group(0).strip():
            break
        stripped.append(m.group(0).strip())
        text = text[m.end():]

    text = _TRAILING_POLITENESS.sub("", text).strip()

    # Restore sentence case. The generator lowercases the first word after prepending a
    # lead-in ("Cho tôi biết: gross Booking Value..."), so without this the canonical form
    # of V2 differs from V1 by exactly one character -- enough to miss the cache.
    if text and text[0].islower():
        text = text[0].upper() + text[1:]

    if not text:
        text = original

    return CanonicalQuery(text=text, original=original, scope=scope,
                          stripped=tuple(stripped))
